name: "LSVerifier Action"
author: "Goblin57"
description: "Uses LSVerifier to verify ANSI-C projects"
runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.lsverifier_options }}
inputs:
    lsverifier_options:
        description: "Options to be used with LSVerifier."
        required: false